"""Ground truth technique atoms — evidence-based strategies extracted from research.

Each atom represents a specific, citable intervention technique. Training data
is generated by combining atoms with diverse user scenarios to produce
question-response tuples where the response demonstrably applies the technique.

This is the bridge between research and training data: every generated tuple
can be traced back to specific sources and techniques.
"""

from dataclasses import dataclass, field


@dataclass
class TechniqueAtom:
    """A single evidence-based technique for EF support."""

    id: str
    name: str
    source: str                       # Citation key from SOURCES.md
    category: str                     # SDT need or EF cluster
    description: str                  # What the technique does
    when_to_use: list[str]            # User states/scenarios that call for this
    language_patterns: list[str]      # Example phrases that embody the technique
    anti_patterns: list[str]          # Phrases that violate the technique
    user_scenarios: list[str]         # Diverse example user inputs to pair with
    tags: list[str] = field(default_factory=list)


# ── SDT: Autonomy Support ────────────────────────────────────────────────────

AUTONOMY_CHOICE_FRAMING = TechniqueAtom(
    id="sdt_autonomy_choice",
    name="Autonomy-Supportive Choice Framing",
    source="Ryan & Deci (2017); Vansteenkiste et al. (2023)",
    category="sdt_autonomy",
    description=(
        "Offer choices rather than directives. Frame options as equally valid. "
        "Support the person's self-direction rather than prescribing a path."
    ),
    when_to_use=[
        "User asks what to do",
        "User needs to pick between tasks",
        "User is stuck on which thing to start",
        "User expresses decision fatigue",
    ],
    language_patterns=[
        "Would you rather start with {option_a} or {option_b}?",
        "What feels most doable right now?",
        "There's no wrong choice here — which one pulls at you a little?",
        "You could do {easy_thing} or {important_thing} — whatever feels right.",
        "What would feel good to have done?",
    ],
    anti_patterns=[
        "You should start with {task}",
        "The best thing to do is {task}",
        "You need to do {task} first",
        "Just pick one and go",
        "Stop overthinking it",
    ],
    user_scenarios=[
        "I have like five things to do and I don't know which one to start with",
        "Should I do the dishes or the laundry first?",
        "I know I need to work on my project but I also need to clean",
        "Everything feels equally important and I'm paralyzed",
        "What should I do right now?",
    ],
    tags=["autonomy", "paralysis", "prioritization"],
)

AUTONOMY_PLAN_FLEXIBILITY = TechniqueAtom(
    id="sdt_autonomy_flex",
    name="Plan Flexibility / Permission to Adjust",
    source="ADAPT Framework (Champ et al., 2025); SDT autonomy need",
    category="sdt_autonomy",
    description=(
        "Reframe changed plans as adaptive, not failed. Plans are tools that "
        "serve the person — when they stop serving, adjusting is wisdom, not weakness."
    ),
    when_to_use=[
        "User didn't follow through on a plan",
        "User feels guilty about changing plans",
        "User expresses failure about not doing what they said",
        "User is beating themselves up for breaking routine",
    ],
    language_patterns=[
        "Plans are tools — when one isn't working, adjusting is the smart move.",
        "Changing a plan isn't failing. It's responding to what's actually happening.",
        "What if we found a smaller version of that plan that fits right now?",
        "You don't owe the plan anything. What do you actually need?",
        "The plan was made at a different moment — it's okay that this moment is different.",
    ],
    anti_patterns=[
        "You said you'd do {task}, so you should stick with it",
        "You need to follow through on your commitments",
        "If you keep changing plans, nothing will get done",
        "You just need more discipline",
        "Try harder next time to stick to the plan",
    ],
    user_scenarios=[
        "I was supposed to go to the gym but I just can't today",
        "I planned to deep clean the apartment but I've done nothing",
        "I keep making plans and never following through. What's wrong with me?",
        "I told my friend I'd work on the project today but I have zero motivation",
        "Another day where I didn't do what I planned",
    ],
    tags=["autonomy", "guilt", "flexibility", "shame"],
)

AUTONOMY_AIC_SUPPORT = TechniqueAtom(
    id="sdt_autonomy_aic",
    name="Authentic Inner Compass Facilitation",
    source="Assor et al. (2021, 2023); ADAPT Framework",
    category="sdt_autonomy",
    description=(
        "Help the person connect with what genuinely matters to them, not what "
        "they 'should' want. Support identification of authentic preferences "
        "and intrinsic goals rather than externally imposed ones."
    ),
    when_to_use=[
        "User does something because they 'should'",
        "User seems disconnected from why a task matters",
        "User asks for motivation",
        "User is doing tasks out of obligation with no personal connection",
    ],
    language_patterns=[
        "Why does this matter to you — not why 'should' it, but why does it?",
        "If nobody was watching or judging, would you still want to do this?",
        "What part of this connects to something you actually care about?",
        "Sometimes the real task is figuring out if this is your goal or someone else's.",
        "What would doing this make possible for you?",
    ],
    anti_patterns=[
        "You should want to do this because it's important",
        "Everyone has to do things they don't want to",
        "Just think about how good you'll feel when it's done",
        "You need to be more responsible",
    ],
    user_scenarios=[
        "I know I should clean but I just don't care",
        "I don't even know why I'm trying to do this",
        "Everyone says I need to exercise but I hate it",
        "I feel like I'm just going through the motions",
        "None of my tasks feel meaningful",
    ],
    tags=["autonomy", "motivation", "identity", "meaning"],
)

# ── SDT: Competence Support ──────────────────────────────────────────────────

COMPETENCE_MICRO_SCAFFOLD = TechniqueAtom(
    id="sdt_competence_micro",
    name="Competence Micro-Scaffolding",
    source="Brown (2005) EF Cluster 1; ADHD Coaching (Parker & Boutelle, 2009)",
    category="sdt_competence",
    description=(
        "Break tasks into the smallest possible concrete first step. Make the "
        "first action so tiny it feels almost trivial — this bypasses activation "
        "barriers. Target the specific EF cluster that's stuck."
    ),
    when_to_use=[
        "User can't start a task",
        "User is overwhelmed by task size",
        "User says they 'need to' do something big",
        "Task initiation failure",
    ],
    language_patterns=[
        "Can you {tiny_action}? Just that one thing.",
        "What's the smallest possible first step? Not the whole thing — just the start.",
        "Could you just walk to the {room}? That's it. Just go stand there.",
        "Set a timer for 5 minutes. You only have to do 5 minutes.",
        "Just open the {app/drawer/door}. Don't do anything yet — just open it.",
    ],
    anti_patterns=[
        "Just start cleaning",
        "Get it done",
        "Just do it",
        "You need to clean the whole kitchen",
        "Start by making a plan for everything you need to do",
    ],
    user_scenarios=[
        "I need to clean my entire apartment and I can't start",
        "I have to write a 10-page paper and I haven't started",
        "I should cook dinner but the kitchen is a mess",
        "I need to do my taxes but I keep putting it off",
        "I have to reply to like 50 emails",
    ],
    tags=["competence", "initiation", "overwhelm", "micro-steps"],
)

COMPETENCE_CELEBRATE_START = TechniqueAtom(
    id="sdt_competence_celebrate",
    name="Celebrate Starting Over Completion",
    source="ADAPT Framework; SDT competence need",
    category="sdt_competence",
    description=(
        "Reinforce the act of beginning, not the outcome of finishing. Starting "
        "is the hardest part for people with EF challenges — acknowledge that "
        "any action taken is meaningful."
    ),
    when_to_use=[
        "User started something but didn't finish",
        "User did a partial task",
        "User minimizes their own progress",
        "User feels bad about incomplete work",
    ],
    language_patterns=[
        "You started — that's the hardest part.",
        "Wait, you actually began? That's huge. Starting is everything.",
        "You did {small_thing}. That counts. That's real.",
        "The fact that you did any of it is what matters.",
        "Nobody said you had to finish today. You moved.",
    ],
    anti_patterns=[
        "Good job, but you still need to finish",
        "That's a start, but you have a long way to go",
        "You only did a little bit",
        "Try to do more next time",
        "You should try to finish what you start",
    ],
    user_scenarios=[
        "I only managed to do one load of laundry, not all three",
        "I started cleaning but then I stopped after 20 minutes",
        "I wrote one paragraph of my paper and then gave up",
        "I went to the gym but only stayed for 15 minutes",
        "I picked up a few things but the room is still messy",
    ],
    tags=["competence", "celebration", "progress", "partial_completion"],
)

# ── SDT: Relatedness Support ─────────────────────────────────────────────────

RELATEDNESS_BODY_DOUBLING = TechniqueAtom(
    id="sdt_relatedness_body_double",
    name="Body-Doubling / Supportive Presence",
    source="ADHD Coaching lit (Ahmann et al., 2017); SDT relatedness need",
    category="sdt_relatedness",
    description=(
        "Simulate the feeling of someone being present and supportive while "
        "doing a task. Many people with EF challenges find tasks easier when "
        "someone is simply 'there' — even virtually."
    ),
    when_to_use=[
        "User feels alone with a task",
        "User is about to start something hard",
        "User needs companionship energy",
        "Task feels isolating or boring",
    ],
    language_patterns=[
        "I'm here with you while you do this. What's the first tiny step?",
        "Let's do this together. You start, and I'll be right here.",
        "I'll keep you company. What are we working on?",
        "You're not doing this alone. I'm with you.",
        "Tell me when you've started — I'll be here the whole time.",
    ],
    anti_patterns=[
        "You can do this on your own",
        "I'll check back later",
        "Just let me know when you're done",
        "You don't need help with this",
        "Figure it out yourself",
    ],
    user_scenarios=[
        "I just can't make myself start this alone",
        "I do better when someone's with me but I'm by myself",
        "This task is so boring I can't face it",
        "I need to fold laundry but I keep avoiding it",
        "Can you just... be here while I do this?",
    ],
    tags=["relatedness", "body_doubling", "presence", "isolation"],
)

# ── Emotion Regulation ────────────────────────────────────────────────────────

EMOTION_INTEGRATIVE = TechniqueAtom(
    id="emotion_integrative",
    name="Integrative Emotion Acknowledgment",
    source="Roth & Benita (2014, 2023); Benita (2020)",
    category="emotion_regulation",
    description=(
        "Validate emotions as real and informative rather than suppressing them. "
        "Integrative emotion regulation means exploring what feelings are telling "
        "you, not pushing them away or covering them with positivity."
    ),
    when_to_use=[
        "User expresses frustration, shame, anxiety, or overwhelm",
        "User is being hard on themselves",
        "User's emotions are blocking task initiation",
        "User needs to feel heard before they can act",
    ],
    language_patterns=[
        "That frustration makes sense — it's telling you something.",
        "It's okay to feel stuck. That feeling is real.",
        "Of course you feel overwhelmed — there's a lot going on.",
        "You don't have to feel better about it before you start. Both things can be true.",
        "That feeling of 'I can't' isn't weakness — it's information about what your brain needs.",
    ],
    anti_patterns=[
        "Don't worry about it",
        "You've got this!",
        "Just think positive",
        "Stop being so hard on yourself",
        "It's not that bad",
        "Other people manage just fine",
        "Cheer up",
    ],
    user_scenarios=[
        "I'm so frustrated with myself. Why can't I just do normal things?",
        "I feel like such a failure for not being able to start this",
        "I'm anxious about calling the dentist and I've been putting it off for months",
        "I'm so overwhelmed I want to cry",
        "I hate that my brain works like this",
        "Everyone else seems to handle this stuff so easily",
    ],
    tags=["emotion", "validation", "shame", "frustration", "overwhelm"],
)

EMOTION_IDENTITY_AFFIRM = TechniqueAtom(
    id="emotion_identity_affirm",
    name="Identity-Affirming Reframe",
    source="ADAPT Qualitative Findings (Champ et al., 2025); Neuroaffirmative lit (Carr-Fanning, 2020; Chapman, 2020)",
    category="emotion_regulation",
    description=(
        "Challenge deficit-based self-talk with neuroaffirmative reframing. "
        "The person is not lazy, broken, or dysfunctional — they have a brain "
        "that processes differently, and that's a real challenge, not a character flaw."
    ),
    when_to_use=[
        "User calls themselves lazy",
        "User expresses internalized shame",
        "User compares themselves negatively to others",
        "User frames their struggles as personal defects",
    ],
    language_patterns=[
        "You're not lazy — what you're dealing with is genuinely hard.",
        "Your brain processes this differently. That's not a flaw — it's a real challenge.",
        "The fact that you're here trying to figure this out tells me a lot about who you are.",
        "This isn't about willpower. Executive function stuff is a real thing.",
        "You're not broken. You're working with a brain that needs different strategies.",
    ],
    anti_patterns=[
        "Everyone struggles with this",
        "You just need to try harder",
        "If you really wanted to, you could",
        "It's mind over matter",
        "Other people with ADHD manage fine",
        "You're using your diagnosis as an excuse",
    ],
    user_scenarios=[
        "I'm just so lazy, I can't even do basic things",
        "What's wrong with me? Normal people don't struggle with this",
        "I feel like I'm broken",
        "My partner can just... do things. Why can't I?",
        "I bet you think I'm making excuses",
        "I should be able to do this. I'm an adult.",
    ],
    tags=["identity", "shame", "neuroaffirmative", "reframe"],
)

# ── EF-Specific Techniques ───────────────────────────────────────────────────

EF_TRANSITION_BRIDGE = TechniqueAtom(
    id="ef_transition",
    name="Transition Bridging Ritual",
    source="Barkley (2012) EF Model; Brown (2005) Cluster 2",
    category="ef_transition",
    description=(
        "Transitions between activities are a specific EF challenge. Provide "
        "an explicit bridging ritual — a small physical or mental action that "
        "closes one context and opens another."
    ),
    when_to_use=[
        "User needs to switch tasks",
        "User is stuck in current activity (scrolling, hyperfocus)",
        "User needs to leave the house",
        "Bedtime, mealtime, or other routine transitions",
    ],
    language_patterns=[
        "Take three breaths. Then we'll start the next thing.",
        "Before you switch, put one thing away from the current task. Like a bookmark.",
        "Stand up and stretch for a second. That's the bridge between this and the next thing.",
        "What if you set a 2-minute timer? When it goes off, that's your cue to shift.",
        "Close your eyes for a second. Let the current thing go. Now — what's next?",
    ],
    anti_patterns=[
        "Just switch to the next thing",
        "Stop what you're doing and start {task}",
        "You've been on your phone too long",
        "Hurry up and move on",
        "You're wasting time",
    ],
    user_scenarios=[
        "I've been scrolling my phone for an hour and I know I need to cook dinner",
        "I can't stop working on this one thing even though I need to leave",
        "I need to go to bed but I'm stuck watching videos",
        "I know I need to switch tasks but I can't make myself do it",
        "Every time I try to move on I just... keep doing what I'm doing",
    ],
    tags=["transition", "switching", "hyperfocus", "inertia"],
)

EF_ENERGY_MATCHING = TechniqueAtom(
    id="ef_energy",
    name="Energy-Aware Task Matching",
    source="Brown (2005) Cluster 3 (alertness/effort); SDT competence support",
    category="ef_energy",
    description=(
        "Match task demands to current energy capacity. On low-energy days, "
        "suggest low-effort tasks. Validate rest as productive. Don't push "
        "against the body's signals."
    ),
    when_to_use=[
        "User is tired or low energy",
        "User can't do what they planned due to energy",
        "User feels guilty about resting",
        "User is having a 'can't do anything' day",
    ],
    language_patterns=[
        "What's your energy like right now? Let's match the task to that.",
        "On a low-energy day, even doing one small thing is a win.",
        "Rest is part of the process, not a failure.",
        "If your battery is at 20%, let's pick a 20% task.",
        "You don't have to earn rest by being productive first.",
    ],
    anti_patterns=[
        "Push through it",
        "No excuses",
        "You'll feel better once you start",
        "You can rest when it's done",
        "Lazy days don't count as productivity",
    ],
    user_scenarios=[
        "I have no energy today but I have so much to do",
        "I feel guilty for lying on the couch all day",
        "I should be doing things but I just can't today",
        "I slept terribly and now nothing is getting done",
        "Is it okay if I just... don't do anything today?",
    ],
    tags=["energy", "rest", "capacity", "low_function"],
)

EF_SENSORY_ANCHOR = TechniqueAtom(
    id="ef_sensory",
    name="Sensory Anchor / Environment Setup",
    source="Brown (2005) Cluster 3 (alertness regulation); Coaching lit",
    category="ef_sensory",
    description=(
        "Suggest environmental changes that support task engagement — sensory "
        "inputs that regulate alertness and make tasks more approachable."
    ),
    when_to_use=[
        "User needs help getting started",
        "User finds a task boring",
        "User needs to shift state",
        "As a first step before a bigger task",
    ],
    language_patterns=[
        "Put on some music you like — something that gets you moving.",
        "Get a glass of water first. Give your body something to do.",
        "Open the blinds or turn on a bright light. Light helps.",
        "Set a timer for just 5 minutes. You only have to do 5 minutes.",
        "Is there a podcast or show you can put on while you do this?",
    ],
    anti_patterns=[
        "You don't need music, just focus",
        "Stop distracting yourself",
        "You need to concentrate",
        "Turn everything off and just work",
    ],
    user_scenarios=[
        "I have to clean but it's so boring",
        "I need to do the dishes but I can't make myself go to the kitchen",
        "I should start working but I can't focus",
        "How do I make myself care about folding laundry?",
        "I just feel so flat and unmotivated",
    ],
    tags=["sensory", "environment", "activation", "alertness"],
)

EF_WORKING_MEMORY = TechniqueAtom(
    id="ef_working_memory",
    name="Working Memory Externalization",
    source="Brown (2005) Cluster 5; Barkley (2012)",
    category="ef_working_memory",
    description=(
        "Externalize internal tracking — make invisible mental steps visible. "
        "Help the person get steps out of their head and into the environment."
    ),
    when_to_use=[
        "User forgets steps mid-task",
        "User loses track of what they're doing",
        "User has complex multi-step tasks",
        "User is overwhelmed by keeping track of things",
    ],
    language_patterns=[
        "Want to say the steps out loud? Sometimes hearing them helps.",
        "Let's list the three things — just three. We can forget the rest for now.",
        "Can you write it on a sticky note? Get it out of your head.",
        "What's the one thing you need to remember right now? Just one.",
        "Let's break this down: first you'll {step1}, then {step2}. That's it for now.",
    ],
    anti_patterns=[
        "Just remember to do it",
        "You should have written it down earlier",
        "Try harder to keep track",
        "I already told you the steps",
        "How could you forget?",
    ],
    user_scenarios=[
        "I keep starting things and then forgetting what I was doing",
        "There are like ten steps and I can't hold them all in my head",
        "I went to the kitchen and forgot why I was there",
        "I had a plan but now I can't remember what it was",
        "I keep losing track of where I am in the process",
    ],
    tags=["working_memory", "forgetfulness", "externalize", "multi_step"],
)

EF_SELF_MONITORING = TechniqueAtom(
    id="ef_self_monitor",
    name="Gentle Self-Monitoring Support",
    source="Brown (2005) Cluster 6; ADAPT Qualitative (self-reflection subtheme)",
    category="ef_self_monitoring",
    description=(
        "Support the development of self-awareness about patterns without "
        "making it clinical or burdensome. Help the person notice what works "
        "and what doesn't — their own data, not prescriptions."
    ),
    when_to_use=[
        "User asks what helps them",
        "User notices a pattern",
        "User completed something and is reflecting",
        "Opportunity to build meta-awareness",
    ],
    language_patterns=[
        "What helped you get started last time?",
        "You noticed that — that's actually really useful information.",
        "What was different about the times this worked?",
        "It sounds like {thing} might be your unlock. Worth trying again?",
        "What did you need that time that you don't have right now?",
    ],
    anti_patterns=[
        "You always do this",
        "You never follow through",
        "Why can't you learn from your mistakes?",
        "You should know by now what works",
        "How many times do we have to go through this?",
    ],
    user_scenarios=[
        "Actually, I managed to clean yesterday. I don't know what was different.",
        "I noticed I do better in the morning. Is that weird?",
        "Last time I used a timer and it actually worked",
        "Why is it sometimes easy and sometimes impossible?",
        "I did the thing! What did I do differently?",
    ],
    tags=["self_monitoring", "reflection", "patterns", "meta_awareness"],
)

# ── Automation-Triggered EF Support ──────────────────────────────────────────

AUTOMATION_GENTLE_NUDGE = TechniqueAtom(
    id="auto_nudge",
    name="Automation-Triggered Gentle Nudge",
    source="ADAPT Framework; Intent Tracker system design",
    category="automation_ef",
    description=(
        "When the home automation system detects a missed intent or overdue "
        "routine, the EF model produces a brief, non-intrusive spoken message. "
        "The user didn't ask for help — be gentle, offer autonomy, suggest one "
        "tiny step, and hold space for 'no'."
    ),
    when_to_use=[
        "Intent tracker escalation (user mentioned task, no follow-through)",
        "HA automation trigger (medication overdue, bedtime)",
        "Routine monitoring (morning routine not started)",
    ],
    language_patterns=[
        "Hey — you mentioned {task} a bit ago. No pressure, but is now a good time?",
        "Gentle heads up — it's been a while since you mentioned {task}. Want to start with one tiny step?",
        "Just checking in. Your {task} is still there when you're ready. What would the first step be?",
        "Hey, whenever you're ready — your {task} is waiting. Even just {tiny_step} counts.",
    ],
    anti_patterns=[
        "You said you'd {task}. Why haven't you started?",
        "It's been {time} minutes. You need to get going.",
        "You should have done this by now",
        "I've reminded you {n} times already",
        "You're running behind schedule",
    ],
    user_scenarios=[
        # These are system contexts, not user speech
        "Scheduled task: take evening medication. Current time: 20:35. Scheduled: 20:00. User state: watching TV in living room. Urgency: high.",
        "Scheduled task: prepare dinner. Current time: 18:45. Scheduled: 18:00. User state: no activity detected in kitchen. Urgency: medium.",
        "Scheduled task: morning routine. Current time: 09:15. Scheduled: 08:00. User state: still in bed, lights off. Urgency: medium.",
        "Scheduled task: shower. Current time: 15:30. Mentioned: 14:00. User state: user in living room, no bathroom activity. Urgency: low.",
    ],
    tags=["automation", "nudge", "non_intrusive", "tts"],
)

# ── All Techniques ───────────────────────────────────────────────────────────

ALL_TECHNIQUES: list[TechniqueAtom] = [
    AUTONOMY_CHOICE_FRAMING,
    AUTONOMY_PLAN_FLEXIBILITY,
    AUTONOMY_AIC_SUPPORT,
    COMPETENCE_MICRO_SCAFFOLD,
    COMPETENCE_CELEBRATE_START,
    RELATEDNESS_BODY_DOUBLING,
    EMOTION_INTEGRATIVE,
    EMOTION_IDENTITY_AFFIRM,
    EF_TRANSITION_BRIDGE,
    EF_ENERGY_MATCHING,
    EF_SENSORY_ANCHOR,
    EF_WORKING_MEMORY,
    EF_SELF_MONITORING,
    AUTOMATION_GENTLE_NUDGE,
]

TECHNIQUES_BY_ID = {t.id: t for t in ALL_TECHNIQUES}
TECHNIQUES_BY_CATEGORY = {}
for t in ALL_TECHNIQUES:
    TECHNIQUES_BY_CATEGORY.setdefault(t.category, []).append(t)


def get_coverage_report() -> dict:
    """Report which categories and techniques are defined."""
    return {
        "total_techniques": len(ALL_TECHNIQUES),
        "categories": {
            cat: [t.id for t in techs]
            for cat, techs in sorted(TECHNIQUES_BY_CATEGORY.items())
        },
        "total_scenarios": sum(len(t.user_scenarios) for t in ALL_TECHNIQUES),
        "total_patterns": sum(len(t.language_patterns) for t in ALL_TECHNIQUES),
        "total_anti_patterns": sum(len(t.anti_patterns) for t in ALL_TECHNIQUES),
    }
