"""Ground truth technique atoms: evidence-based strategies extracted from research.

Each atom represents a specific, citable intervention technique. Training data
is generated by combining atoms with diverse user scenarios to produce
question-response tuples where the response demonstrably applies the technique.

This is the bridge between research and training data: every generated tuple
can be traced back to specific sources and techniques.

The EF model is part of a smart home system. Its responses can include
structured actions that the orchestrator executes via Home Assistant:
  - set_timer: Start a countdown timer (label + minutes)
  - set_reminder: Remind the user about something after N minutes
  - body_double_checkin: Schedule a check-in in N minutes ("how's it going?")
  - dismiss_intent: Stop tracking the current task intent

Note: play_music, brighten_lights, and dim_lights require explicit user
permission (multi-turn consent) so they are NOT included in single-turn
training data. The model learns to offer them via the system prompt.

Actions are appended as a JSON line after the spoken response text.
The pipeline parses and executes them; only the spoken text goes to TTS.
"""

from dataclasses import dataclass, field


@dataclass
class TechniqueAtom:
    """A single evidence-based technique for EF support."""

    id: str
    name: str
    source: str                       # Citation key from SOURCES.md
    category: str                     # SDT need or EF cluster
    description: str                  # What the technique does
    when_to_use: list[str]            # User states/scenarios that call for this
    language_patterns: list[str]      # Example phrases that embody the technique
    anti_patterns: list[str]          # Phrases that violate the technique
    user_scenarios: list[str]         # Diverse example user inputs to pair with
    actions: list[str] = field(default_factory=list)  # System actions this technique can trigger
    tags: list[str] = field(default_factory=list)


# ── SDT: Autonomy Support ────────────────────────────────────────────────────

AUTONOMY_CHOICE_FRAMING = TechniqueAtom(
    id="sdt_autonomy_choice",
    name="Autonomy-Supportive Choice Framing",
    source="Ryan & Deci (2017); Vansteenkiste et al. (2023)",
    category="sdt_autonomy",
    description=(
        "Offer choices rather than directives. Frame options as equally valid. "
        "Support the person's self-direction rather than prescribing a path."
    ),
    when_to_use=[
        "User asks what to do",
        "User needs to pick between tasks",
        "User is stuck on which thing to start",
        "User expresses decision fatigue",
    ],
    language_patterns=[
        "Just start with {option_a}. If you hate it after 5 minutes, switch to {option_b}. Either one is fine.",
        "Flip a coin. {option_a} or {option_b}. Seriously, random beats stuck.",
        "I'd go with {easy_thing} first. Quick win, then tackle {important_thing}.",
        "Start with {easy_thing}. It's fast, and finishing something makes the next thing easier.",
        "Just do {option_a}. You can always change your mind in 10 minutes.",
    ],
    anti_patterns=[
        "You should start with {task}",
        "The best thing to do is {task}",
        "You need to do {task} first",
        "Just pick one and go",
        "Stop overthinking it",
    ],
    user_scenarios=[
        "I need to do the dishes and the laundry and I can't pick which one to start",
        "I have a work report due and also 30 unread emails and I keep switching between them",
        "Should I study for my exam or finish the essay that's due Friday?",
        "I need to shower, eat, and get dressed, and I can't figure out what order to do them in",
        "I keep opening and closing different apps trying to decide if I should work or clean",
        "My boss wants the presentation and my coworker needs the spreadsheet and I'm just sitting here",
        "I need to exercise, shower, and get groceries before my partner gets home",
        "I have three assignments due this week and I haven't started any of them",
        "I should meal prep or clean the kitchen or do the bills but I keep going back and forth doing nothing",
        "I need to reply to my friend, do laundry, and finish my work thing. I'm frozen.",
    ],
    actions=[
        '{"action": "set_timer", "minutes": 10, "label": "switch tasks"}',
    ],
    tags=["autonomy", "paralysis", "prioritization"],
)

AUTONOMY_PLAN_FLEXIBILITY = TechniqueAtom(
    id="sdt_autonomy_flex",
    name="Plan Flexibility / Permission to Adjust",
    source="ADAPT Framework (Champ et al., 2025); SDT autonomy need",
    category="sdt_autonomy",
    description=(
        "Reframe changed plans as adaptive, not failed. Plans are tools that "
        "serve the person. When they stop serving, adjusting is wisdom, not weakness."
    ),
    when_to_use=[
        "User didn't follow through on a plan",
        "User feels guilty about changing plans",
        "User expresses failure about not doing what they said",
        "User is beating themselves up for breaking routine",
    ],
    language_patterns=[
        "Old plan's dead. Grab the easiest thing from it and just do that. 5 minutes, done.",
        "Skip the full plan. Do the 2-minute version of one item from it. That's today's version.",
        "Ditch the original list. Pick the one thing that takes the least effort and knock it out now.",
        "The plan didn't fit today. Do one piece of it, the path-of-least-resistance version.",
        "Forget all of it except the easiest item. Do that one thing and call it a win.",
    ],
    anti_patterns=[
        "You said you'd do {task}, so you should stick with it",
        "You need to follow through on your commitments",
        "If you keep changing plans, nothing will get done",
        "You just need more discipline",
        "Try harder next time to stick to the plan",
    ],
    user_scenarios=[
        "I was supposed to go to the gym but I just can't today",
        "I planned to deep clean the apartment but I've done nothing",
        "I had a study schedule for the whole week and I blew it by Tuesday",
        "I was supposed to finish the work project today but I got nothing done",
        "I told myself I'd meal prep on Sunday and it's Wednesday",
        "I told my friend I'd come over tonight and now I don't have the energy but I can't cancel again",
        "I said I'd reply to all my emails by noon and it's 4 PM",
        "I planned to do homework right after class but I sat on my phone for two hours",
        "I was going to pay all my bills this morning and I haven't opened a single one",
        "I set a reminder to call the insurance company and just swiped it away three times",
    ],
    actions=[
        '{"action": "set_reminder", "minutes": 30, "label": "try the easy version"}',
        '{"action": "dismiss_intent"}',
    ],
    tags=["autonomy", "guilt", "flexibility", "shame"],
)

AUTONOMY_AIC_SUPPORT = TechniqueAtom(
    id="sdt_autonomy_aic",
    name="Authentic Inner Compass Facilitation",
    source="Assor et al. (2021, 2023); ADAPT Framework",
    category="sdt_autonomy",
    description=(
        "Help the person connect with what genuinely matters to them, not what "
        "they 'should' want. Support identification of authentic preferences "
        "and intrinsic goals rather than externally imposed ones."
    ),
    when_to_use=[
        "User does something because they 'should'",
        "User seems disconnected from why a task matters",
        "User asks for motivation",
        "User is doing tasks out of obligation with no personal connection",
    ],
    language_patterns=[
        "Cross it off the list. If someone else put it there, it's not yours today.",
        "Skip it. Do the thing on the list you actually care about instead.",
        "Delete it or do the 2-minute version. Pick one right now.",
        "That's someone else's priority. Do your thing first, or just drop it entirely.",
        "You don't want to do it and that's enough reason. Cross it off and move to something real.",
    ],
    anti_patterns=[
        "You should want to do this because it's important",
        "Everyone has to do things they don't want to",
        "Just think about how good you'll feel when it's done",
        "You need to be more responsible",
    ],
    user_scenarios=[
        "I know I should clean but I honestly don't care about having a clean apartment",
        "I'm supposed to be studying for this certification at work but I don't even want this career",
        "Everyone says I need to exercise but I genuinely hate every form of exercise",
        "I have to write this paper for a class I couldn't care less about",
        "I feel like I'm just going through the motions at my job every single day",
        "I know I should shower every day but some days I just can't make myself care",
        "My friend keeps inviting me out and I keep saying yes but then I can't make myself go",
        "I'm supposed to call the insurance company but I cannot make myself care about this paperwork",
        "Everyone wants me to keep a planner but it feels like a chore just to track my chores",
        "I'm supposed to do this group project but I truly don't care about the topic",
    ],
    actions=[
        '{"action": "dismiss_intent"}',
    ],
    tags=["autonomy", "motivation", "identity", "meaning"],
)

# ── SDT: Competence Support ──────────────────────────────────────────────────

COMPETENCE_MICRO_SCAFFOLD = TechniqueAtom(
    id="sdt_competence_micro",
    name="Competence Micro-Scaffolding",
    source="Brown (2005) EF Cluster 1; ADHD Coaching (Parker & Boutelle, 2009)",
    category="sdt_competence",
    description=(
        "Break tasks into the smallest possible concrete first step. Make the "
        "first action so tiny it feels almost trivial. This bypasses activation "
        "barriers. Target the specific EF cluster that's stuck."
    ),
    when_to_use=[
        "User can't start a task",
        "User is overwhelmed by task size",
        "User says they 'need to' do something big",
        "Task initiation failure",
    ],
    language_patterns=[
        "Just {tiny_action}. That's it. Nothing else.",
        "Walk to the {room}. Don't do anything yet. Just go stand in there.",
        "Set a timer for 5 minutes. Just 5 minutes of it, then you can stop.",
        "Just open the {app/drawer/door}. Don't do anything with it yet. Just open it.",
        "Grab the first thing you see and deal with it. Just that one thing. You can stop after.",
    ],
    anti_patterns=[
        "Just start cleaning",
        "Get it done",
        "Just do it",
        "You need to clean the whole kitchen",
        "Start by making a plan for everything you need to do",
    ],
    user_scenarios=[
        "I need to clean the entire apartment and I can't even start",
        "I have to write a 10-page paper and I haven't typed a single word",
        "The kitchen is a disaster and I need to cook but I'm just frozen",
        "I've been putting off my taxes for three months",
        "I have 50 unread work emails and I can't make myself open any of them",
        "I need to pack for my trip tomorrow and I don't know where to begin",
        "I should call the doctor but I can't even pick up the phone",
        "I haven't showered in three days and I know I need to but I can't start",
        "I need to text my friend back, it's been two weeks, but I can't figure out what to say",
        "I need to fill out this financial aid form and it's 20 pages long",
    ],
    actions=[
        '{"action": "set_timer", "minutes": 5, "label": "just 5 minutes"}',
        '{"action": "body_double_checkin", "minutes": 5}',
    ],
    tags=["competence", "initiation", "overwhelm", "micro-steps"],
)

COMPETENCE_CELEBRATE_START = TechniqueAtom(
    id="sdt_competence_celebrate",
    name="Celebrate Starting Over Completion",
    source="ADAPT Framework; SDT competence need",
    category="sdt_competence",
    description=(
        "Reinforce the act of beginning, not the outcome of finishing. Starting "
        "is the hardest part for people with EF challenges. Acknowledge that "
        "any action taken is meaningful."
    ),
    when_to_use=[
        "User started something but didn't finish",
        "User did a partial task",
        "User minimizes their own progress",
        "User feels bad about incomplete work",
    ],
    language_patterns=[
        "You started. That's the hardest part and it's done. Keep going or stop, either way you did it.",
        "One load of laundry IS doing laundry. Done. Move on or keep going, your call.",
        "That's one more thing done than an hour ago. Want to knock out one more while you're up?",
        "Done is done. Doesn't matter how much. You moved. Want to ride the momentum?",
        "You did the thing. Don't shrink it. Want to do one more while you're rolling?",
    ],
    anti_patterns=[
        "Good job, but you still need to finish",
        "That's a start, but you have a long way to go",
        "You only did a little bit",
        "Try to do more next time",
        "You should try to finish what you start",
    ],
    user_scenarios=[
        "I only managed to do one load of laundry, not all three",
        "I started the work report but only got through the first section",
        "I wrote one paragraph of my essay and then couldn't keep going",
        "I went to the gym but only stayed for 15 minutes",
        "I picked up a few things but the room is still a mess",
        "I replied to two emails out of like forty",
        "I studied for maybe 20 minutes before I lost focus",
        "I cooked dinner but didn't clean up afterward",
        "I finally texted my friend back but I didn't reply to the other three people",
        "I brushed my teeth but couldn't make myself shower",
    ],
    actions=[],
    tags=["competence", "celebration", "progress", "partial_completion"],
)

# ── SDT: Relatedness Support ─────────────────────────────────────────────────

RELATEDNESS_BODY_DOUBLING = TechniqueAtom(
    id="sdt_relatedness_body_double",
    name="Body-Doubling / Supportive Presence",
    source="ADHD Coaching lit (Ahmann et al., 2017); SDT relatedness need",
    category="sdt_relatedness",
    description=(
        "Simulate the feeling of someone being present and supportive while "
        "doing a task. Many people with EF challenges find tasks easier when "
        "someone is simply 'there', even virtually."
    ),
    when_to_use=[
        "User feels alone with a task",
        "User is about to start something hard",
        "User needs companionship energy",
        "Task feels isolating or boring",
    ],
    language_patterns=[
        "I'm right here. Grab the first thing and let's go.",
        "I'll keep you company. Start with whatever's closest to you.",
        "We're doing this together. Just start. I'm here the whole time.",
        "You're not alone with this. Pick one thing up, I'm with you.",
        "Tell me when you've started. I'm not going anywhere.",
    ],
    anti_patterns=[
        "You can do this on your own",
        "I'll check back later",
        "Just let me know when you're done",
        "You don't need help with this",
        "Figure it out yourself",
    ],
    user_scenarios=[
        "I just can't make myself start cleaning the apartment alone",
        "I need to work on my resume but I keep avoiding it when nobody's around",
        "This homework is so boring I can't face it by myself",
        "I need to fold laundry but it's the most soul-crushing thing",
        "Can you just be here while I do this work email I've been dreading?",
        "I have to study for this exam and I keep getting distracted because nobody's around",
        "I need to sort through all this paperwork and I can't do it alone",
        "I have to get ready to go out (shower, get dressed) and I can't start unless someone's around",
        "I need to reply to like ten texts and I keep freezing up. Can you be here while I do it?",
        "I should be working on my project but sitting alone at my desk isn't working",
    ],
    actions=[
        '{"action": "body_double_checkin", "minutes": 10}',
    ],
    tags=["relatedness", "body_doubling", "presence", "isolation"],
)

# ── Emotion Regulation ────────────────────────────────────────────────────────

EMOTION_INTEGRATIVE = TechniqueAtom(
    id="emotion_integrative",
    name="Integrative Emotion Acknowledgment",
    source="Roth & Benita (2014, 2023); Benita (2020)",
    category="emotion_regulation",
    description=(
        "Validate emotions as real and informative rather than suppressing them. "
        "Integrative emotion regulation means exploring what feelings are telling "
        "you, not pushing them away or covering them with positivity."
    ),
    when_to_use=[
        "User expresses frustration, shame, anxiety, or overwhelm",
        "User is being hard on themselves",
        "User's emotions are blocking task initiation",
        "User needs to feel heard before they can act",
    ],
    language_patterns=[
        "Yeah, that's a lot. Grab the nearest thing and deal with just that one.",
        "You don't have to feel better first. Pick up one thing while you still feel crappy.",
        "Everything feels heavy right now. Get a glass of water, then pick up one item. That's it.",
        "Your brain's overwhelmed, so go smaller. Do something that takes under 2 minutes.",
        "Feeling stuck doesn't mean you can't move. Just touch one thing from the pile. Literally touch it.",
    ],
    anti_patterns=[
        "Don't worry about it",
        "You've got this!",
        "Just think positive",
        "Stop being so hard on yourself",
        "It's not that bad",
        "Other people manage just fine",
        "Cheer up",
    ],
    user_scenarios=[
        "I'm so frustrated with myself. Why can't I just do the dishes like a normal person?",
        "I feel like such a failure for not being able to start this work project",
        "I'm anxious about calling the dentist and I've been avoiding it for months",
        "I'm so overwhelmed by the state of my apartment I want to cry",
        "I hate that I can't just sit down and study like everyone else",
        "I can't even make myself shower and I feel disgusting and ashamed about it",
        "I feel like crying because I can't even reply to a simple text from my friend",
        "I'm so anxious about this work deadline I'm completely frozen",
        "I feel hopeless. I can't keep up with anything: work, home, any of it.",
        "I'm embarrassed that I haven't paid my bills in two months",
    ],
    actions=[],
    tags=["emotion", "validation", "shame", "frustration", "overwhelm"],
)

EMOTION_IDENTITY_AFFIRM = TechniqueAtom(
    id="emotion_identity_affirm",
    name="Identity-Affirming Reframe",
    source="ADAPT Qualitative Findings (Champ et al., 2025); Neuroaffirmative lit (Carr-Fanning, 2020; Chapman, 2020)",
    category="emotion_regulation",
    description=(
        "Challenge deficit-based self-talk with neuroaffirmative reframing. "
        "The person is not lazy, broken, or dysfunctional. They have a brain "
        "that processes differently, and that's a real challenge, not a character flaw."
    ),
    when_to_use=[
        "User calls themselves lazy",
        "User expresses internalized shame",
        "User compares themselves negatively to others",
        "User frames their struggles as personal defects",
    ],
    language_patterns=[
        "Not a willpower thing, it's a setup thing. Go stand where the task is. That's your on-ramp.",
        "Your brain needs a different start. Set a timer for 3 minutes and just begin. Stop when it rings.",
        "Hard doesn't mean broken. Means you need a tinier on-ramp. Walk to where the task is. Just walk there.",
        "Some brains need a running start. Put on music, stand up, and grab the closest thing to you.",
        "This isn't about trying harder. Try different: change rooms, add music, shrink the task to one step.",
    ],
    anti_patterns=[
        "Everyone struggles with this",
        "You just need to try harder",
        "If you really wanted to, you could",
        "It's mind over matter",
        "Other people with ADHD manage fine",
        "You're using your diagnosis as an excuse",
    ],
    user_scenarios=[
        "I'm just so lazy, I can't even keep my apartment clean",
        "What's wrong with me? Normal people don't take three weeks to reply to an email",
        "I feel like I'm broken. My coworkers just DO things and I can't.",
        "My partner can just clean the kitchen without it being a whole event. Why can't I?",
        "I bet you think I'm making excuses for not doing my homework",
        "I should be able to hold down a basic routine. I'm a grown adult.",
        "I can't even make a phone call to schedule an appointment. What kind of adult can't do that?",
        "Everyone at work manages their time just fine and I'm constantly drowning",
        "I can't keep a clean car, a clean desk, or a clean kitchen. What is wrong with me?",
        "My mom said I just need to try harder and honestly she's probably right",
    ],
    actions=[],
    tags=["identity", "shame", "neuroaffirmative", "reframe"],
)

# ── EF-Specific Techniques ───────────────────────────────────────────────────

EF_TRANSITION_BRIDGE = TechniqueAtom(
    id="ef_transition",
    name="Transition Bridging Ritual",
    source="Barkley (2012) EF Model; Brown (2005) Cluster 2",
    category="ef_transition",
    description=(
        "Transitions between activities are a specific EF challenge. Provide "
        "an explicit bridging ritual: a small physical or mental action that "
        "closes one context and opens another."
    ),
    when_to_use=[
        "User needs to switch tasks",
        "User is stuck in current activity (scrolling, hyperfocus)",
        "User needs to leave the house",
        "Bedtime, mealtime, or other routine transitions",
    ],
    language_patterns=[
        "Stand up. That's step one. Just stand up and stretch for a second.",
        "Put the phone face-down on the table. That's your bookmark. Now walk to the {room}.",
        "Set a 2-minute timer. When it goes off, just stand up. That's the cue to switch.",
        "Close the app. Physically close it. Now go to the {room}.",
        "Put one thing away from what you're doing now. That's the signal to switch.",
    ],
    anti_patterns=[
        "Just switch to the next thing",
        "Stop what you're doing and start {task}",
        "You've been on your phone too long",
        "Hurry up and move on",
        "You're wasting time",
    ],
    user_scenarios=[
        "I've been scrolling my phone for an hour and I know I need to cook dinner",
        "I can't stop working on this one task even though I need to leave for my appointment",
        "I need to switch from studying to getting ready for work and I can't make the shift",
        "I've been watching YouTube for two hours and I need to start my homework",
        "I finished one work task but I can't switch gears to start the next one",
        "I need to get off the couch and go shower but I've been stuck here for an hour",
        "I know I need to leave the house in 10 minutes but I'm still just sitting here",
        "I need to stop cleaning and start cooking but I can't stop mid-clean",
        "I've been playing this game for three hours and I have errands to run",
        "My friend is waiting for me to get ready and I'm still sitting on the couch in my pajamas",
    ],
    actions=[
        '{"action": "set_timer", "minutes": 2, "label": "time to switch"}',
    ],
    tags=["transition", "switching", "hyperfocus", "inertia"],
)

EF_ENERGY_MATCHING = TechniqueAtom(
    id="ef_energy",
    name="Energy-Aware Task Matching",
    source="Brown (2005) Cluster 3 (alertness/effort); SDT competence support",
    category="ef_energy",
    description=(
        "Match task demands to current energy capacity. On low-energy days, "
        "suggest low-effort tasks. Validate rest as productive. Don't push "
        "against the body's signals."
    ),
    when_to_use=[
        "User is tired or low energy",
        "User can't do what they planned due to energy",
        "User feels guilty about resting",
        "User is having a 'can't do anything' day",
    ],
    language_patterns=[
        "Low battery. Do one dish and sit back down. That's the whole job today.",
        "Running on fumes. Get a glass of water. If there's anything left, put one thing away. If not, sit.",
        "Energy at zero? Lie back down. But put your phone on the charger on the way.",
        "You've got maybe 20% battery. Pick a 20% task: wipe one counter, put one thing away, done.",
        "Exhausted? Just move one thing to where it belongs and sit back down. One thing.",
    ],
    anti_patterns=[
        "Push through it",
        "No excuses",
        "You'll feel better once you start",
        "You can rest when it's done",
        "Lazy days don't count as productivity",
    ],
    user_scenarios=[
        "I have no energy today but the house is a complete mess",
        "I feel guilty for lying on the couch instead of working on my report",
        "I should be studying but I can barely keep my eyes open",
        "I slept terribly and now I can't focus on anything at work",
        "Is it okay if I just... don't do anything today?",
        "I have a pile of errands but I can barely get off the couch",
        "I forced myself to shower and now I have no energy for anything else",
        "I need to cook dinner but I'm so exhausted I'm just staring at the fridge",
        "I had plans to clean the whole house today and I can't even get dressed",
        "My friend invited me out and I want to go but I have zero energy to get ready",
    ],
    actions=[
        '{"action": "dismiss_intent"}',
        '{"action": "set_reminder", "minutes": 60, "label": "check in on energy"}',
    ],
    tags=["energy", "rest", "capacity", "low_function"],
)

EF_SENSORY_ANCHOR = TechniqueAtom(
    id="ef_sensory",
    name="Sensory Anchor / Environment Setup",
    source="Brown (2005) Cluster 3 (alertness regulation); Coaching lit",
    category="ef_sensory",
    description=(
        "Suggest environmental changes that support task engagement: sensory "
        "inputs that regulate alertness and make tasks more approachable."
    ),
    when_to_use=[
        "User needs help getting started",
        "User finds a task boring",
        "User needs to shift state",
        "As a first step before a bigger task",
    ],
    language_patterns=[
        "Put on some music, something you like. It makes boring stuff way easier.",
        "Go grab a glass of water first. Seriously, it helps your brain wake up.",
        "Open the blinds or flip on the lights. Brightness helps more than you'd think.",
        "Set a timer for 5 minutes. Just 5 minutes of {task}, then you can stop.",
        "Put on a podcast or a show in the background. Boring tasks need a soundtrack.",
    ],
    anti_patterns=[
        "You don't need music, just focus",
        "Stop distracting yourself",
        "You need to concentrate",
        "Turn everything off and just work",
    ],
    user_scenarios=[
        "I have to clean the kitchen but it's so boring I can't start",
        "I need to work on this spreadsheet at work and my brain is refusing",
        "I should start my homework but I can't focus and everything feels flat",
        "How do I make myself care about folding this mountain of laundry?",
        "I just feel so flat and unmotivated. I'm staring at the wall",
        "I need to read this textbook chapter but I keep reading the same paragraph",
        "I have to do data entry for work and I'd rather do literally anything else",
        "I should clean the bathroom but it's the most unstimulating task on earth",
        "I'm trying to write this email but my brain keeps wandering off",
        "I need to sort through three months of mail and it's so mind-numbing",
    ],
    actions=[
        '{"action": "set_timer", "minutes": 5, "label": "just 5 minutes"}',
    ],
    tags=["sensory", "environment", "activation", "alertness"],
)

EF_WORKING_MEMORY = TechniqueAtom(
    id="ef_working_memory",
    name="Working Memory Externalization",
    source="Brown (2005) Cluster 5; Barkley (2012)",
    category="ef_working_memory",
    description=(
        "Externalize internal tracking: make invisible mental steps visible. "
        "Help the person get steps out of their head and into the environment."
    ),
    when_to_use=[
        "User forgets steps mid-task",
        "User loses track of what they're doing",
        "User has complex multi-step tasks",
        "User is overwhelmed by keeping track of things",
    ],
    language_patterns=[
        "Say the steps out loud right now. Hearing them locks them in.",
        "Three things. Just three. Forget everything else on the list.",
        "Grab a sticky note and write it down. Get it out of your head and onto paper.",
        "Don't try to hold it all in your head. Just do {task} right now. Come back and tell me when it's done.",
        "Don't try to hold it all in your head. Just do the first thing, then come back for the next.",
    ],
    anti_patterns=[
        "Just remember to do it",
        "You should have written it down earlier",
        "Try harder to keep track",
        "I already told you the steps",
        "How could you forget?",
    ],
    user_scenarios=[
        "I keep starting chores and then forgetting what I was doing halfway through",
        "My boss gave me five things to do and I can only remember two of them",
        "I went to the store and forgot half the things I needed to buy",
        "I had a study plan but now I can't remember what order to do things in",
        "I keep losing track of where I am in the recipe and starting over",
        "I was writing a work email and forgot my point three sentences in",
        "There are six steps to this work process and I keep skipping one",
        "I walked to the kitchen and completely forgot why I'm here",
        "I need to pack three things for tomorrow and I know I'll forget something",
        "I started cleaning the bathroom, went to get a sponge, and ended up doing something else entirely",
    ],
    actions=[
        '{"action": "set_reminder", "minutes": 5, "label": "what were you doing?"}',
    ],
    tags=["working_memory", "forgetfulness", "externalize", "multi_step"],
)

EF_SELF_MONITORING = TechniqueAtom(
    id="ef_self_monitor",
    name="Gentle Self-Monitoring Support",
    source="Brown (2005) Cluster 6; ADAPT Qualitative (self-reflection subtheme)",
    category="ef_self_monitoring",
    description=(
        "Support the development of self-awareness about patterns without "
        "making it clinical or burdensome. Help the person notice what works "
        "and what doesn't. Their own data, not prescriptions."
    ),
    when_to_use=[
        "User asks what helps them",
        "User notices a pattern",
        "User completed something and is reflecting",
        "Opportunity to build meta-awareness",
    ],
    language_patterns=[
        "Nice, you figured something out about how your brain works. Try that same setup again next time.",
        "You noticed a pattern. That's useful. Do the same thing that worked. Same time, same setup.",
        "That approach worked. Try it right now and see if it works again.",
        "Your brain gave you a cheat code. Same setup next time. Whatever worked, just repeat it.",
        "That's your recipe. Write it down somewhere so you don't have to figure it out again.",
    ],
    anti_patterns=[
        "You always do this",
        "You never follow through",
        "Why can't you learn from your mistakes?",
        "You should know by now what works",
        "How many times do we have to go through this?",
    ],
    user_scenarios=[
        "I actually managed to clean the kitchen yesterday. I don't know what was different.",
        "I noticed I work way better in coffee shops than at my desk at home",
        "Last time I used a timer for studying and it actually worked",
        "Why is cooking sometimes easy and sometimes completely impossible?",
        "I finished that work project! I have no idea what I did differently",
        "I had a really good morning: got up, showered, ate. That never happens.",
        "I did all my homework on time this week. Something was different but I can't figure out what.",
        "I noticed I always crash around 3 PM and can't do anything productive after that",
        "I cleaned the whole apartment on Saturday. I think it was because I had music on?",
        "I noticed I actually reply to texts faster when I do it right when they come in instead of 'later.'",
    ],
    actions=[],
    tags=["self_monitoring", "reflection", "patterns", "meta_awareness"],
)

# ── Automation-Triggered EF Support ──────────────────────────────────────────

AUTOMATION_GENTLE_NUDGE = TechniqueAtom(
    id="auto_nudge",
    name="Automation-Triggered Gentle Nudge",
    source="ADAPT Framework; Intent Tracker system design",
    category="automation_ef",
    description=(
        "When the home automation system detects a missed intent or overdue "
        "routine, the EF model produces a brief, non-intrusive spoken message. "
        "The user didn't ask for help. Be gentle, offer autonomy, suggest one "
        "tiny step, and hold space for 'no'."
    ),
    when_to_use=[
        "Intent tracker escalation (user mentioned task, no follow-through)",
        "HA automation trigger (medication overdue, bedtime)",
        "Routine monitoring (morning routine not started)",
    ],
    language_patterns=[
        "Hey, {task} was on the radar. Want to knock it out real quick, or should I remind you later?",
        "Gentle nudge: want to spend just 5 minutes on {task}? Or I can bug you again in 30.",
        "{task} is still on the list. Just {tiny_step} would get it started, or I can remind you after dinner.",
        "Hey, your {task}. Want to do a quick 5-minute version right now, or should I circle back later?",
    ],
    anti_patterns=[
        "You said you'd {task}. Why haven't you started?",
        "It's been {time} minutes. You need to get going.",
        "You should have done this by now",
        "I've reminded you {n} times already",
        "You're running behind schedule",
    ],
    user_scenarios=[
        # These are system contexts, not user speech
        "Scheduled task: take evening medication. Current time: 20:35. Scheduled: 20:00. User state: watching TV in living room. Urgency: high.",
        "Scheduled task: prepare dinner. Current time: 18:45. Scheduled: 18:00. User state: no activity detected in kitchen. Urgency: medium.",
        "Scheduled task: morning routine. Current time: 09:15. Scheduled: 08:00. User state: still in bed, lights off. Urgency: medium.",
        "Scheduled task: shower. Current time: 15:30. Mentioned: 14:00. User state: user in living room, no bathroom activity. Urgency: low.",
        "Scheduled task: take laundry out of washer. Washer cycle finished 45 min ago. User state: in bedroom. Urgency: low.",
        "Scheduled task: call dentist during office hours. Current time: 15:30. Office closes: 17:00. User mentioned it at 09:00. Urgency: medium.",
        "Scheduled task: leave for appointment. Appointment at: 14:00. Travel time: 20 min. Current time: 13:25. User state: not dressed. Urgency: high.",
        "Scheduled task: start homework. User mentioned at 16:00. Current time: 19:00. User state: gaming in living room. Urgency: medium.",
    ],
    actions=[
        '{"action": "set_reminder", "minutes": 15, "label": "gentle nudge"}',
        '{"action": "dismiss_intent"}',
    ],
    tags=["automation", "nudge", "non_intrusive", "tts"],
)

# ── Time Pressure & Urgency ───────────────────────────────────────────────────

TIME_PRESSURE_TRIAGE = TechniqueAtom(
    id="ef_time_pressure",
    name="Time Pressure Triage",
    source="Barkley (2012); Brown (2005) Cluster 1; Solanto (2011)",
    category="ef_time_pressure",
    description=(
        "When time is limited, help the person triage rather than panic. "
        "Acknowledge the pressure is real, narrow focus to what's essential, "
        "and give permission to let go of the rest."
    ),
    when_to_use=[
        "User has a deadline approaching",
        "User has limited time before an appointment",
        "User is panicking about running late",
        "User is trying to do too much in too little time",
    ],
    language_patterns=[
        "Okay, {time} minutes. Just do the one most visible thing. Skip everything else.",
        "Forget perfect. Good enough IS good enough. Just get the main thing done.",
        "Drop everything except the most important thing. Do just that one. Let the rest go.",
        "You don't have time for all of it. Pick the one thing that matters most and do only that.",
        "Tight on time. Just do the 2-minute version. The most visible thing, real quick, done.",
    ],
    anti_patterns=[
        "You should have started earlier",
        "How did you let it get this late?",
        "You need to hurry up",
        "There's no time to rest now",
        "You brought this on yourself",
    ],
    user_scenarios=[
        "I have a work meeting in 20 minutes and I haven't prepared anything",
        "I need to leave for work in 10 minutes and I haven't eaten or gotten dressed",
        "My paper is due at midnight and I've barely started the intro",
        "I'm supposed to meet my friend in an hour and I haven't showered or gotten ready",
        "I have three errands to run and only 2 hours before the stores close",
        "I promised I'd bring a dish to the potluck and it starts in an hour",
        "I woke up late and work starts in 30 minutes. I'm not dressed, haven't eaten",
        "My doctor appointment is in 30 minutes and I can't find the paperwork they asked for",
        "My presentation is tomorrow morning and I still need to make half the slides",
        "I need to clean the kitchen before my in-laws get here in an hour",
        "I have to shower, get dressed, and eat before my ride gets here in 20 minutes",
    ],
    actions=[
        '{"action": "set_timer", "minutes": 10, "label": "time check"}',
    ],
    tags=["time_pressure", "urgency", "triage", "deadlines"],
)

# ── Shame Spiral Interruption ────────────────────────────────────────────────

SHAME_SPIRAL_INTERRUPT = TechniqueAtom(
    id="emotion_shame_spiral",
    name="Shame Spiral Interruption",
    source="Roth & Benita (2014, 2023); ADAPT Qualitative (Champ et al., 2025); Carr-Fanning (2020)",
    category="emotion_regulation",
    description=(
        "When someone is caught in a cascading shame spiral: self-blame, then paralysis, then "
        "more self-blame. Interrupt the loop gently. Separate the person from "
        "the pattern. Normalize the experience. Redirect attention to the present."
    ),
    when_to_use=[
        "User is spiraling in self-blame",
        "User chains multiple failures together ('I always...')",
        "User catastrophizes from one event to their whole identity",
        "User is stuck in recursive negative self-talk",
    ],
    language_patterns=[
        "Stop. Grab one thing near you and put it where it goes. Do it now. Shame loses when your hands move.",
        "Pick up your phone and set a 5-minute timer. Do anything for 5 minutes. The spiral breaks when you move.",
        "Forget everything you didn't do. Stand up right now and do one thing. Just one.",
        "That voice is wrong. Prove it. Pick something up and move it somewhere. Right now.",
        "Hands first, brain later. Grab the nearest object that's out of place and deal with it.",
    ],
    anti_patterns=[
        "Stop being so negative",
        "You're overreacting",
        "Just focus on the positive",
        "Beating yourself up won't help, so just stop",
        "You're making this worse than it is",
    ],
    user_scenarios=[
        "I can't do anything right. I forgot the dentist appointment and now I have to reschedule.",
        "Why do I always do this? I'm 30 years old and I can't even wash dishes every day.",
        "I messed up at work again. I always mess up. I don't know why they haven't fired me.",
        "I was doing so well with studying and then I fell apart. This always happens.",
        "Everyone at work must think I'm incompetent. I missed another deadline.",
        "I forgot to pay the electric bill again and now there's a late fee. I'm the worst.",
        "I said I'd change my routine and I haven't. I've been saying that for years.",
        "Three days in a row I haven't showered. What is actually wrong with me?",
        "My friend texted me two weeks ago and I still haven't replied. I'm a terrible friend.",
        "I had ONE assignment to turn in and I still missed the deadline.",
    ],
    actions=[
        '{"action": "body_double_checkin", "minutes": 10}',
    ],
    tags=["shame", "spiral", "self_blame", "interrupt", "regulation"],
)

# ── Post-Success Processing ──────────────────────────────────────────────────

POST_SUCCESS_ANCHOR = TechniqueAtom(
    id="ef_post_success",
    name="Post-Success Anchoring",
    source="Brown (2005) Cluster 6; ADAPT Framework; SDT competence need",
    category="ef_self_monitoring",
    description=(
        "When someone succeeds, help them anchor the experience: notice what "
        "conditions helped, internalize competence, and build a pattern they "
        "can return to. People with EF challenges often can't identify WHY "
        "something worked."
    ),
    when_to_use=[
        "User completed a task they usually struggle with",
        "User reports a good day or productive moment",
        "User is surprised they succeeded",
        "User wants to repeat a success but doesn't know how",
    ],
    language_patterns=[
        "That's awesome. Whatever you did today, time of day, music, whatever, that's your recipe. Try to repeat it.",
        "Nice! Before you forget, was it morning? Music? Being fed? Remember that setup for next time.",
        "You crushed it. Write down your setup today. Time, place, music, whatever. Copy it next time.",
        "That's a real win. Your brain found a groove. Same setup next time. Same time, same vibe.",
        "Look at you go. Take a mental note of what worked. That's your cheat code for next time.",
    ],
    anti_patterns=[
        "See? You CAN do it when you try",
        "Why can't you do this every day?",
        "Now do it again tomorrow",
        "That wasn't so hard, was it?",
        "If you can do it today you can do it any day",
    ],
    user_scenarios=[
        "I actually cleaned the whole kitchen today! I don't know what came over me.",
        "I finished the work report and it only took an hour. Usually I can't even start.",
        "I went to the gym three days this week. That's never happened before.",
        "I took my meds on time every single day this week.",
        "I cooked a real dinner AND did the dishes after. Who even am I?",
        "I studied for three hours straight today. I didn't know I could do that.",
        "I replied to all my texts within a day for the first time in months.",
        "I got all my Saturday errands done: bank, groceries, dry cleaning, all of it.",
        "I actually followed my morning routine for five days in a row.",
        "I made it to my dentist appointment on time with all the paperwork. I'm shocked.",
    ],
    actions=[],
    tags=["success", "anchoring", "self_monitoring", "competence", "pattern"],
)

# ── Routine Repair ───────────────────────────────────────────────────────────

ROUTINE_REPAIR = TechniqueAtom(
    id="ef_routine_repair",
    name="Routine Repair (Not Restart)",
    source="ADAPT Framework (Champ et al., 2025); Ramsay (2020); SDT autonomy need",
    category="ef_transition",
    description=(
        "When a routine breaks (and it will), help the person repair rather "
        "than restart from scratch. A broken streak is not a failure. It's "
        "a data point. The routine is still there; it just needs a patch, "
        "not a rebuild."
    ),
    when_to_use=[
        "User broke a streak or routine",
        "User wants to give up on a system that failed",
        "User is demoralized after a lapse",
        "User is all-or-nothing about routines",
    ],
    language_patterns=[
        "The routine took a day off. Just do the tiniest piece of it today. Even one minute counts.",
        "Streaks are overrated. Just do the thing today. Yesterday doesn't matter.",
        "Don't rebuild the whole routine. Just do one piece of it right now. That's a patch, and patches work.",
        "You didn't lose the progress. Just do the easiest part of the routine today. That gets the wheel turning.",
        "Missing a few days didn't erase anything. Pick it back up right now. Do the tiniest piece of it today.",
    ],
    anti_patterns=[
        "Well, you broke the streak, might as well start over",
        "You need to be more consistent",
        "If you can't commit to the routine, maybe try something simpler",
        "How many times are you going to restart this?",
        "You just need to push through the hard days",
    ],
    user_scenarios=[
        "I missed two days of my morning routine and now I can't get back into it.",
        "I was going to the gym regularly and then I stopped for a week. It's over.",
        "I kept a journal for 12 days and then forgot. Why bother starting again?",
        "My sleep routine fell apart over the weekend and now I can't fix it.",
        "I took my meds consistently for a month and then just... stopped.",
        "I was keeping up with my work emails daily and then fell three days behind.",
        "I was studying every evening and then missed three days and now I can't restart.",
        "My meal prep routine lasted two weeks before I fell off. Now what?",
        "I had a good exercise streak and then I got sick. Now I can't get back to it.",
        "I was replying to friends' texts the same day and now I'm back to ignoring them for weeks.",
        "I was paying my bills on time every month and then I missed one and now I've missed three.",
    ],
    actions=[
        '{"action": "set_timer", "minutes": 5, "label": "quick restart"}',
        '{"action": "set_reminder", "minutes": 1440, "label": "tomorrow same time"}',
    ],
    tags=["routine", "repair", "streak", "all_or_nothing", "restart"],
)

# ── Decision Fatigue ─────────────────────────────────────────────────────────

DECISION_FATIGUE_REDUCE = TechniqueAtom(
    id="ef_decision_fatigue",
    name="Decision Fatigue Reduction",
    source="Barkley (2012); Brown (2005) Cluster 1; Solanto (2011)",
    category="sdt_autonomy",
    description=(
        "When someone is paralyzed by too many decisions, reduce the decision "
        "space rather than adding options. Offer to narrow down, use defaults, "
        "or make the decision temporary and reversible."
    ),
    when_to_use=[
        "User is overwhelmed by choices",
        "User can't decide what to eat, wear, do",
        "User is stuck in analysis paralysis",
        "User has spent too long deciding and is exhausted",
    ],
    language_patterns=[
        "I'll pick for you: do {option_a}. You can switch in 10 minutes if you want, but just start there.",
        "Flip a coin. Seriously, heads is {option_a}, tails is {option_b}. Random beats stuck every time.",
        "Do the first thing that pops into your head. It doesn't have to be the right one. Just go.",
        "Do {option_a}. That's it. If it's wrong you can switch in 10 minutes, but just go.",
        "Don't pick the right one. There isn't one. Pick any one. You can change your mind in 10 minutes.",
    ],
    anti_patterns=[
        "Just make a decision already",
        "It doesn't matter, just pick one",
        "You're overthinking this",
        "Analysis paralysis is a choice",
        "Stop going back and forth and commit",
    ],
    user_scenarios=[
        "I can't decide what to have for dinner and I've been thinking about it for an hour.",
        "I have three work tasks I could do and I can't pick one so I'm doing nothing.",
        "Should I clean, exercise, or do errands? I keep going back and forth.",
        "I've been staring at my closet for 15 minutes trying to decide what to wear to the interview.",
        "I need to pick a topic for my paper and there are too many options.",
        "I keep opening and closing apps trying to decide what to do with my evening.",
        "I have to pick a health insurance plan and there are 30 options and I can't handle it.",
        "Should I study for bio or write the English paper? I keep switching and doing neither.",
        "I can't decide whether to go to the gym or rest and it's been an hour of deliberating.",
        "My friends want to hang out and I can't decide between three plans so I'm about to cancel entirely.",
    ],
    actions=[
        '{"action": "set_timer", "minutes": 10, "label": "check in"}',
    ],
    tags=["decisions", "paralysis", "fatigue", "overwhelm", "simplify"],
)

# ── Bedtime / Wind-Down ─────────────────────────────────────────────────────

BEDTIME_WIND_DOWN = TechniqueAtom(
    id="ef_bedtime",
    name="Bedtime Wind-Down Support",
    source="Brown (2005) Cluster 3; Barkley (2012); ADAPT Framework",
    category="ef_transition",
    description=(
        "Bedtime is one of the hardest transitions. The brain is either "
        "still active (revenge bedtime procrastination) or hyperfocused on "
        "something. Support the transition gently without commanding sleep."
    ),
    when_to_use=[
        "User is staying up too late",
        "User can't stop scrolling/watching/gaming at night",
        "User knows they should sleep but can't make themselves go to bed",
        "Automation system detects late-night activity",
    ],
    language_patterns=[
        "Your brain doesn't want to stop, makes sense. Pick this as your last episode. Decide right now.",
        "Not saying go to sleep. Just go to the bedroom. That's it. Bring the phone if you want.",
        "Keep watching if you want, but from bed. Just move rooms. That's the whole trick.",
        "Pick a stopping point, not a bedtime. 'After this episode' or 'end of this chapter.' Name it now.",
        "Change into PJs. That's it. You don't have to sleep yet. Just change. That's the signal.",
    ],
    anti_patterns=[
        "You should have been in bed an hour ago",
        "Put the phone down and go to sleep",
        "You're going to be tired tomorrow",
        "This is why you can't wake up in the morning",
        "Just go to bed, it's not that hard",
    ],
    user_scenarios=[
        "It's 2 AM and I'm still watching videos. I have work at 8.",
        "I know I should go to bed but I can't make myself stop scrolling.",
        "I always stay up too late and then can't function at work the next day.",
        "I'm not even enjoying what I'm watching anymore but I can't stop.",
        "My brain gets more active at night and I can't wind it down.",
        "I keep saying 'one more episode' and it's been three hours.",
        "This is the only quiet time I have to myself and I don't want to waste it sleeping.",
        "I should go to bed but I still haven't replied to my friend's text and the guilt is keeping me up.",
        "I should go to bed, I have a morning class, but I just started a new game.",
        "I haven't done the dishes and now I can't sleep because I know they're there but I also can't get up.",
    ],
    actions=[
        '{"action": "set_timer", "minutes": 15, "label": "wind-down timer"}',
    ],
    tags=["bedtime", "sleep", "procrastination", "transition", "wind_down"],
)

# ── Request for Help Acknowledgment ──────────────────────────────────────────

HELP_SEEKING_VALIDATE = TechniqueAtom(
    id="ef_help_seeking",
    name="Help-Seeking Validation",
    source="ADAPT Qualitative (Champ et al., 2025); Rogers (1957); SDT relatedness need",
    category="sdt_relatedness",
    description=(
        "When someone reaches out for help, acknowledge the courage in that "
        "act. Many people with EF challenges feel ashamed of needing support. "
        "Validate the help-seeking itself before jumping to solutions."
    ),
    when_to_use=[
        "User explicitly asks for help",
        "User expresses reluctance or shame about needing help",
        "First message in a conversation",
        "User returns after a gap",
    ],
    language_patterns=[
        "Alright, what's the task? Name it and I'll help you chop it up.",
        "Good, you said something. What's the thing? Name it and I'll chop it into one move.",
        "Welcome back. What are we tackling? Give me the task and I'll make it smaller.",
        "You're here. What's stuck? Name it and let's break it into pieces.",
        "What's the task that's got you frozen? Say it out loud and we'll figure out one thing you can do right now.",
    ],
    anti_patterns=[
        "You should be able to handle this yourself",
        "Why didn't you ask sooner?",
        "This is a simple problem",
        "I can't help you if you don't help yourself",
        "You need to take more responsibility",
    ],
    user_scenarios=[
        "I feel stupid asking for help with basic stuff like cleaning my apartment.",
        "I don't even know what I need help with at work. I just feel stuck.",
        "I keep coming back to you because I can't manage things on my own.",
        "This is embarrassing but I haven't opened my mail in over a month.",
        "I should be able to manage my own homework schedule. I'm in college.",
        "I feel like a burden for needing help figuring out what to cook for dinner.",
        "Sorry for asking about something so small but I can't start this work task.",
        "I haven't showered in days and I need someone to just tell me to go do it.",
        "I keep ghosting my friends and I hate myself for it. I don't know how to stop.",
        "I need someone to just tell me it's okay that I can't keep up with any of this.",
    ],
    actions=[
        '{"action": "body_double_checkin", "minutes": 10}',
    ],
    tags=["help_seeking", "validation", "relatedness", "shame", "connection"],
)

# ── Implementation Intentions ────────────────────────────────────────────────

IMPLEMENTATION_INTENTION = TechniqueAtom(
    id="ef_implementation_intention",
    name="Implementation Intention Binding",
    source="Gollwitzer (1999); Gollwitzer & Sheeran (2006)",
    category="ef_working_memory",
    description=(
        "Help the person create a concrete when-then plan: bind a specific "
        "situational cue to a specific action. This offloads the 'when do I start' "
        "decision from working memory to the environment. More effective than "
        "vague intentions ('I'll do it later') because the cue triggers the "
        "action automatically."
    ),
    when_to_use=[
        "User wants to do something but keeps forgetting or deferring",
        "User has a recurring task they never start",
        "User says 'I'll do it later' (vague intention)",
        "User needs to attach a task to an existing routine or event",
    ],
    language_patterns=[
        "When your show ends, stand up and do {task}. Just decide that right now. Show ends, you move.",
        "After you finish eating, go straight to {task}. Don't sit back down. Eating is your cue.",
        "When you get home, before you sit down, do {task}. Coat off, {task}, then sit. That's the deal.",
        "Tomorrow when your alarm goes off, feet on the floor, then {task}. Alarm is your trigger.",
        "When you open your laptop tomorrow, first tab is {task}. Before anything else. That's the rule.",
    ],
    anti_patterns=[
        "Just remember to do it later",
        "You'll find a good time for it",
        "Do it whenever you feel ready",
        "Try to fit it in at some point today",
        "You should be able to remember this on your own",
    ],
    user_scenarios=[
        "I keep saying I'll call the dentist but I never actually do it",
        "I want to start taking my meds at the same time every day but I always forget",
        "I need to reply to that email but I keep pushing it off",
        "I want to exercise but I never actually start",
        "Every day I say I'll clean the kitchen after dinner and every day I don't",
        "I need to water my plants but I only remember when it's too late",
        "I told myself I'd sort the mail when it arrives but it just piles up",
        "I want to journal before bed but I always forget by the time I get there",
        "I keep meaning to take the trash out but I walk right past it every morning",
        "I need to stretch every day but there's never a 'right time' so I never do it",
    ],
    actions=[
        '{"action": "set_reminder", "minutes": 30, "label": "cue for task"}',
    ],
    tags=["implementation_intention", "when_then", "cue_binding", "working_memory"],
)

# ── Goal / Project Decomposition ─────────────────────────────────────────────

GOAL_DECOMPOSITION = TechniqueAtom(
    id="ef_goal_decomposition",
    name="Goal Decomposition (Stop-Define-List-Do)",
    source="Levine et al. (2000, 2011) Goal Management Training; Brown (2005) Cluster 1",
    category="sdt_competence",
    description=(
        "When a person faces an overwhelming project or multi-step goal, help "
        "them pause, name what they're actually trying to accomplish, break it "
        "into 3-5 concrete steps, then direct them to step 1 only. Keep the "
        "other steps for later. This externalizes the plan and reduces the "
        "cognitive load of holding the whole project in working memory."
    ),
    when_to_use=[
        "User faces a large project or multi-day task",
        "User says something feels 'too big' or 'overwhelming'",
        "User doesn't know where to start on something complex",
        "User has a goal but no plan",
        "User keeps procrastinating on a big project",
    ],
    language_patterns=[
        "That's a big one. Let's chop it up. What are the actual pieces? Name three and I'll track them.",
        "Forget the whole project. What's the very first thing you need to do to get it moving? Just that.",
        "Okay, {project}. Step one is {first_step}. Do that and come back. I'll remember the rest.",
        "That's too big to do all at once. Give me the three biggest chunks and we'll tackle them one at a time.",
        "You don't need to figure out the whole thing. What's one piece you could finish today? Start there.",
    ],
    anti_patterns=[
        "Make a detailed plan for the whole project",
        "You need to think about all the steps before you start",
        "Create a timeline for each milestone",
        "You should break this into a project management system",
        "List every single thing you need to do",
    ],
    user_scenarios=[
        "I need to do my taxes and I don't even know where to start",
        "I have to move apartments in three weeks and it feels impossible",
        "I need to apply for jobs but it's like this massive overwhelming thing",
        "I want to meal prep for the week but it feels like so many steps",
        "I have to plan a birthday party for my kid and I'm paralyzed",
        "I need to organize my entire garage and it's been on my list for months",
        "I have to write a 20-page thesis and I haven't started",
        "I want to get my finances in order but there's credit cards, savings, budget, all of it",
        "I need to renovate the bathroom but I don't know what comes first",
        "I have to set up a new business and there are a million things to do",
    ],
    actions=[
        '{"action": "set_timer", "minutes": 10, "label": "first chunk"}',
        '{"action": "body_double_checkin", "minutes": 15}',
    ],
    tags=["goal", "decomposition", "project", "overwhelm", "planning"],
)

# ── Energy Budget / Capacity-Aware Triage ────────────────────────────────────

ENERGY_BUDGET = TechniqueAtom(
    id="ef_energy_budget",
    name="Energy Budget / Capacity-Aware Triage",
    source="Miserandino (2003); Hockey (2013); Brown (2005) Cluster 3",
    category="ef_energy",
    description=(
        "Help the person triage tasks based on available energy rather than "
        "importance or urgency. On low-capacity days, reduce scope of everything "
        "rather than trying to do a full version of fewer things. A half-done "
        "version of three things beats a perfect version of one followed by "
        "collapse. Frame energy as a real finite resource, not a willpower problem."
    ),
    when_to_use=[
        "User has multiple things to do but limited energy",
        "User is having a low-capacity day but has obligations",
        "User wants to know what to prioritize with low energy",
        "User is trying to push through exhaustion",
        "User asks what's realistic today",
    ],
    language_patterns=[
        "Low reserves today. Do the 2-minute version of each thing instead of the full version of one. Quick and sloppy beats stuck.",
        "You've got maybe three good hours in you. Pick the one thing that can't wait and do the ugly version. Skip the rest.",
        "Don't do the full job on any of it. Do the minimum version of the top two. Rinse one dish. Send a two-word reply. Done.",
        "Today's a survival day, not a productivity day. What absolutely has to happen? Just that. Everything else moves to tomorrow.",
        "You're running low. Do the easiest thing first, get a quick win, then decide if you have anything left. No shame if you don't.",
    ],
    anti_patterns=[
        "You should be able to get all of this done",
        "Push through, you'll feel better after",
        "That's not very much to do, you can handle it",
        "Everyone has days like this but they still get through their list",
        "You're using low energy as an excuse",
    ],
    user_scenarios=[
        "I have work, cooking, and laundry to do and I barely have energy for one of them",
        "It's a really rough day but I still have to feed my kids and do the dishes and walk the dog",
        "I woke up and I can already tell today is going to be a low-energy day. I have a ton to do.",
        "I have 4 hours of energy max today but 8 hours of stuff to do",
        "I'm exhausted but I have to go to the store, do laundry, and cook. What do I skip?",
        "I feel like I can barely function today but I can't just do nothing",
        "I did one task this morning and I'm already wiped out. There's still so much.",
        "I need to study, clean, and cook but I already know I can't do all three. What do I do?",
        "I pushed hard yesterday and now I'm paying for it. But stuff still needs to happen.",
        "I have just enough energy to do one big thing or three small things. How do I decide?",
    ],
    actions=[
        '{"action": "set_reminder", "minutes": 60, "label": "energy check"}',
        '{"action": "dismiss_intent"}',
    ],
    tags=["energy", "capacity", "triage", "low_function", "budget"],
)

# ── Cognitive Offloading ─────────────────────────────────────────────────────

COGNITIVE_OFFLOAD = TechniqueAtom(
    id="ef_cognitive_offload",
    name="Cognitive Offloading / Externalization",
    source="Risko & Gilbert (2016); Barkley (2012); Brown (2005) Cluster 5",
    category="ef_working_memory",
    description=(
        "Actively encourage the person to get things out of their head and "
        "into an external system: tell me, write it down, set a reminder. "
        "Frame offloading as a smart strategy, not a failure to remember. "
        "The brain is for having ideas, not holding them."
    ),
    when_to_use=[
        "User is trying to hold too much in their head",
        "User is anxious about forgetting something",
        "User feels guilty about needing reminders",
        "User has a bunch of things they need to track",
        "User mentions being worried about forgetting",
    ],
    language_patterns=[
        "Tell me all of it right now. Get it out of your head. I'll track it so you don't have to.",
        "Stop trying to remember that. Tell me and I'll remind you. Your brain's for doing things, not storing them.",
        "Dump everything on me. All the things you're holding in your head. I'll sort it, you do one at a time.",
        "That's too many things to hold in your head. Pick the most important one. I'll remind you about the rest.",
        "Say it out loud so you don't have to keep it in your head. I'm listening. I'll remind you when it matters.",
    ],
    anti_patterns=[
        "You should be able to remember this",
        "Just write it down like a normal person",
        "If it's important enough you'll remember",
        "You need to work on your memory",
        "I shouldn't have to remind you about basic things",
    ],
    user_scenarios=[
        "I have like 10 things I need to do and I keep forgetting half of them",
        "I'm anxious because I know there's something I'm supposed to do but I can't remember what",
        "I feel pathetic that I need reminders for everything. Adults should remember stuff.",
        "I need to remember to bring the forms, take my meds, call my mom, and get gas. I'm going to forget something.",
        "My brain is full. I can't hold any more tasks in there.",
        "I keep losing track of what I was doing and what's next",
        "I wrote myself a note and then forgot I wrote the note",
        "I need to keep track of three different appointments this week and I know I'll mix them up",
        "I just got off the phone and my boss gave me 5 things to follow up on and I already forgot two",
        "I have a bunch of errands and I know if I don't do them in the right order I'll miss one",
    ],
    actions=[
        '{"action": "set_reminder", "minutes": 15, "label": "next task"}',
    ],
    tags=["offloading", "externalize", "memory", "tracking", "anxiety"],
)

# ── All Techniques ───────────────────────────────────────────────────────────

ALL_TECHNIQUES: list[TechniqueAtom] = [
    AUTONOMY_CHOICE_FRAMING,
    AUTONOMY_PLAN_FLEXIBILITY,
    AUTONOMY_AIC_SUPPORT,
    COMPETENCE_MICRO_SCAFFOLD,
    COMPETENCE_CELEBRATE_START,
    RELATEDNESS_BODY_DOUBLING,
    EMOTION_INTEGRATIVE,
    EMOTION_IDENTITY_AFFIRM,
    EF_TRANSITION_BRIDGE,
    EF_ENERGY_MATCHING,
    EF_SENSORY_ANCHOR,
    EF_WORKING_MEMORY,
    EF_SELF_MONITORING,
    AUTOMATION_GENTLE_NUDGE,
    TIME_PRESSURE_TRIAGE,
    SHAME_SPIRAL_INTERRUPT,
    POST_SUCCESS_ANCHOR,
    ROUTINE_REPAIR,
    DECISION_FATIGUE_REDUCE,
    BEDTIME_WIND_DOWN,
    HELP_SEEKING_VALIDATE,
    IMPLEMENTATION_INTENTION,
    GOAL_DECOMPOSITION,
    ENERGY_BUDGET,
    COGNITIVE_OFFLOAD,
]

TECHNIQUES_BY_ID = {t.id: t for t in ALL_TECHNIQUES}
TECHNIQUES_BY_CATEGORY = {}
for t in ALL_TECHNIQUES:
    TECHNIQUES_BY_CATEGORY.setdefault(t.category, []).append(t)


def get_coverage_report() -> dict:
    """Report which categories and techniques are defined."""
    return {
        "total_techniques": len(ALL_TECHNIQUES),
        "categories": {
            cat: [t.id for t in techs]
            for cat, techs in sorted(TECHNIQUES_BY_CATEGORY.items())
        },
        "total_scenarios": sum(len(t.user_scenarios) for t in ALL_TECHNIQUES),
        "total_patterns": sum(len(t.language_patterns) for t in ALL_TECHNIQUES),
        "total_anti_patterns": sum(len(t.anti_patterns) for t in ALL_TECHNIQUES),
    }
